### ISSUE TITLE
Google Play Store icons

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#1022]
I collected them from individual screenshots and de-duplicated them:

http://i.imgur.com/fJ2qRIE.png

As text list (with aliases):
- [x] food & drink
- [x] women / female https://materialdesignicons.com/icon/gender-female
- [x] pulse (variant) / health / fitness #1016
- [ ] house and garden / plant / flower
- [x] men / male https://materialdesignicons.com/icon/gender-male
- [x] news / politics https://materialdesignicons.com/icon/newspaper / #1003 
- [ ] special interest
- [ ] entertainment / ticket (variant)
- [x] science & technoloy / idea / innovation https://materialdesignicons.com/icon/lightbulb
- [ ] books / reference books / book-open-bookmark
- [ ] comics / thought balloon/bubble
- [ ] history / script / paper scroll https://materialdesignicons.com/icon/script as filled version?
- [ ] belletristic & literature / feather & inkwell #691?
- [ ] crime fiction & thrillers / search-crosshair / magnify-target?
- [x] advisers / book-bookmark https://materialdesignicons.com/icon/book
- [ ] travel / flight (variant) / airplane
- [ ] economy & funds / chart-bar-box https://materialdesignicons.com/icon/poll-box ?
- [ ] action & adventure / map & boxing glove
- [x] animation movies / rocket https://materialdesignicons.com/icon/rocket (allthought slightly different)
- [x] documentation / account-search #990 
- [ ] drama / play/theater (sad)
- [ ] family https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-170745882
- [ ] horror / play/theather (scary)
- [ ] comedy / play/theater (happy)
- [ ] crime movies / shield-star #1017 
- [ ] sci-fi & fantasy / planet / saturn
- [ ] reality- & game shows / account-tv
- [ ] adventure / map-treasure #555?
- [ ] action / boxing-glove
- [ ] arcade / joystick
- [x] board games / dice https://materialdesignicons.com/icon/dice-5
- [x] puzzle / waiting games https://materialdesignicons.com/icon/puzzle (perhaps we want a variant?)
- [ ] casual games / gamepad-face / controller-smile?
- [ ] card games / playing-cards
- [ ] casino / chip?
- [x] learning games https://materialdesignicons.com/icon/school
- [ ] music #932 
- [ ] quiz games #647 
- [x] racing / car sport https://materialdesignicons.com/icon/steering (update / have a variant?)
- [ ] role-playing games / RPG / sword & shield
- [ ] strategy / chess #555 
- [ ] word riddles / w-box?
- [ ] media & video https://materialdesignicons.com/icon/movie (have a variant with an open clapper?)
- [x] medicine https://materialdesignicons.com/icon/pharmazy (have a variant?)
- [ ] software & trials
- [x] games https://materialdesignicons.com/icon/google-controller
- [x] tools / wrench https://materialdesignicons.com/icon/build
- [x] weather https://materialdesignicons.com/icon/weather-partlycloudy
- [ ] similar #982 
- [ ] family-friendly / star-face https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-170745882
- [x] efficiency / circle-check https://materialdesignicons.com/icon/checkbox-marked-circle-outline
- [ ] finance / chart (variant) https://materialdesignicons.com/icon/chart-areaspline should do
- [x] photography / camera https://materialdesignicons.com/icon/camera (although it's a bit different)
- [ ] lifestyle / account-home
- [ ] live backgrounds / image-record-box (the small circle is important here!)
- [ ] customization / account-cog #841 
- [x] widgets / cog-box https://materialdesignicons.com/icon/settings-box

Music:
- [ ] alternative/indie / guitar
- [ ] blues / microphone (variant)
- [ ] country / guitar (variant)
- [ ] dance/electronic / turntable
- [x] easy listening / candle
- [ ] folk
- [ ] spiritual music / harp
- [ ] heavy metal / guitar (variant)
- [x] hip-hop/rap / boombox
- [x] jazz / saxophone
- [x] classical music / cello
- [ ] music and radio plays for children
- [ ] pop / microphone (variant)
- [ ] R&B / soul / piano
- [ ] raggae / drums / percussion
- [ ] rock / guitar (variant)
- [x] schlager/folk / headphones https://materialdesignicons.com/icon/headphones
- [ ] soundtracks / filmstrip-music-notes?

BTW: I was pretty sure I posted that picture link before, but it seems like it disappeared. I'm also missing a post of mine in which I provided a few recreated icons from Google Photos app... Did GitHub mess it up?!

**Comment by infanf** [comment]
![animation](https://cloud.githubusercontent.com/assets/8826710/13034433/f87071c6-d335-11e5-8d7e-9c84a7b4aa18.png) ![animation-48](https://cloud.githubusercontent.com/assets/8826710/13034434/f871ade8-d335-11e5-848f-460e963fce33.png) ![animation-96](https://cloud.githubusercontent.com/assets/8826710/13034435/f8756974-d335-11e5-8aa1-ae9faf4b0e9b.png)
![boombox](https://cloud.githubusercontent.com/assets/8826710/13034436/f877d646-d335-11e5-8206-bda237732e48.png) ![boombox-48](https://cloud.githubusercontent.com/assets/8826710/13034437/f87b259e-d335-11e5-9bca-0ac7e93420c5.png) ![boombox-96](https://cloud.githubusercontent.com/assets/8826710/13034438/f87db606-d335-11e5-83f5-8ab73fe79e1e.png)
![candle](https://cloud.githubusercontent.com/assets/8826710/13034439/f887e860-d335-11e5-8cee-8bf6385eb2f4.png) ![candle-48](https://cloud.githubusercontent.com/assets/8826710/13034440/f8881fd8-d335-11e5-9b81-cac6a3045ca5.png) ![candle-96](https://cloud.githubusercontent.com/assets/8826710/13034441/f88d3108-d335-11e5-91f0-f4d6a600c9c1.png)
![food](https://cloud.githubusercontent.com/assets/8826710/13034442/f88e2284-d335-11e5-8ff8-38009b3c8bf4.png) ![food-48](https://cloud.githubusercontent.com/assets/8826710/13034444/f893c4c8-d335-11e5-8672-e3607b462abb.png) ![food-96](https://cloud.githubusercontent.com/assets/8826710/13034443/f89288d8-d335-11e5-839e-72e2a2bb04e6.png)
![health](https://cloud.githubusercontent.com/assets/8826710/13034445/f89f499c-d335-11e5-8a4f-e70dcb9ba5ba.png) ![health-48](https://cloud.githubusercontent.com/assets/8826710/13034446/f8a1299c-d335-11e5-808b-e796815f2832.png) ![health-96](https://cloud.githubusercontent.com/assets/8826710/13034447/f8a42aa2-d335-11e5-88f3-ef956cd7cc8b.png)
![saxophone](https://cloud.githubusercontent.com/assets/8826710/13034448/f8a634e6-d335-11e5-8dc8-7749b68281c1.png) ![saxophone-48](https://cloud.githubusercontent.com/assets/8826710/13034449/f8aae608-d335-11e5-8fda-fc666af894a3.png) ![saxophone-96](https://cloud.githubusercontent.com/assets/8826710/13034450/f8ab2a28-d335-11e5-9540-188b269958ea.png)
![story](https://cloud.githubusercontent.com/assets/8826710/13034452/f8b6ad30-d335-11e5-8804-92fca508c655.png) ![story-48](https://cloud.githubusercontent.com/assets/8826710/13034451/f8b67810-d335-11e5-992b-45441329ab0f.png) ![story-96](https://cloud.githubusercontent.com/assets/8826710/13034453/f8bcd21e-d335-11e5-8486-ba249a111a64.png)
![violin](https://cloud.githubusercontent.com/assets/8826710/13034454/f8bd875e-d335-11e5-95bc-6fef3366b6d3.png) ![violin-48](https://cloud.githubusercontent.com/assets/8826710/13034456/f8c2fcac-d335-11e5-8439-fa0a5339830e.png) ![violin-96](https://cloud.githubusercontent.com/assets/8826710/13034455/f8c1afd2-d335-11e5-9cc5-3aedf7fce6dd.png)
[icons.zip](https://github.com/Templarian/MaterialDesign/files/129727/icons.zip)

**Comment by Templarian** [comment]
[![animation](https://materialdesignicons.com/icon/animation)](https://materialdesignicons.com/icon/animation) [![boombox](https://materialdesignicons.com/icon/boombox)](https://materialdesignicons.com/icon/boombox) [![candle](https://materialdesignicons.com/icon/candle)](https://materialdesignicons.com/icon/candle)  [![food-fork-drink](https://materialdesignicons.com/icon/food-fork-drink)](https://materialdesignicons.com/icon/food-fork-drink) [![heart-pulse](https://materialdesignicons.com/icon/heart-pulse)](https://materialdesignicons.com/icon/heart-pulse) [![saxophone](https://materialdesignicons.com/icon/saxophone)](https://materialdesignicons.com/icon/saxophone) [![book-open-page-variant](https://materialdesignicons.com/icon/book-open-page-variant)](https://materialdesignicons.com/icon/book-open-page-variant) [![violin](https://materialdesignicons.com/icon/violin)](https://materialdesignicons.com/icon/violin)

**Comment by CoDEmanX** [comment]
@infanf: make you check https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-179558442 to not re-create icons we already have contributions for - unless you enjoy it very much :wink:

**Comment by Templarian** [comment]
I assigned these all to Google. Got mixed up jumping back and forth between issues.

Oversight on my part.

**Comment by anjocerdena** [comment]
I'm contributing new and old icons from the nav drawer of the Play Store (version 6.4.12).

[Play Store icons.zip](https://github.com/Templarian/MaterialDesign/files/225877/Play.Store.icons.zip)

![image](https://cloud.githubusercontent.com/assets/15527344/14639511/b9f093d2-066f-11e6-8af0-4eb1c0cb96b0.png)

**Comment by infanf** [comment]
The new Play Music icon in the Playstore ist quite similar to the existing _music-circle_ icon.

![music-circle](https://cloud.githubusercontent.com/assets/8826710/14640530/3eb0667a-0642-11e6-9fa5-76ff894a027f.png) ![play-music-96](https://cloud.githubusercontent.com/assets/8826710/14640534/4418d7be-0642-11e6-8de3-1392c0240c5e.png)
music-circle | play-music

![music-compare](https://cloud.githubusercontent.com/assets/8826710/14640611/962b2ffc-0642-11e6-9ad8-f37e0d9df0f3.png)

Anyway, here's the new play music Icon
[play-music.zip](https://github.com/Templarian/MaterialDesign/files/225947/play-music.zip)

![play-music](https://cloud.githubusercontent.com/assets/8826710/14640622/ae007aec-0642-11e6-9065-60227fe9ed82.png)![play-music-48](https://cloud.githubusercontent.com/assets/8826710/14640623/ae01a480-0642-11e6-8043-6c42d2d4005d.png)![play-music-96](https://cloud.githubusercontent.com/assets/8826710/14640624/ae058d48-0642-11e6-8e1d-705fbec4c033.png)

**Comment by CoDEmanX** [comment]
The notes in both look different from these still: #783

**Comment by infanf** [comment]
Nevertheless the left one is the currently existing mdi icon, the one in the right the new Play Music icon on https://play.google.com

**Comment by infanf** [comment]
Might be due to the resolution difference

**Comment by Templarian** [comment]
Added the `note-circle` icon.

Closing... if there was one that needed to be tracked we can create separate issues. These mega issues get too difficult to track.
