### ISSUE TITLE
music-clef-alto

### ISSUE THREAD

**Issue by pattyjogal** [Templarian/MaterialDesign#1036]
I think many music composition/theory apps would benefit greatly from these icons.

Here are some for clefs and accidentals:
- [x] [Treble](https://upload.wikimedia.org/wikipedia/commons/f/fa/Treble_clef.svg) - _Will be added in #3263_
- [x] [Bass](https://upload.wikimedia.org/wikipedia/commons/6/61/Bass_clef.svg) - _Will be added in #3263_
- [ ] [Alto](https://upload.wikimedia.org/wikipedia/commons/5/5a/Alto_clef.svg)
- [x] Sharp : &#9839; - _Will be added in #3263_
- [x] Flat : &#9837; - _Will be added in #3263_
- [x] Natural : &#9838; - _Will be added in #3263_

**Comment by Templarian** [comment]
Can you edit your comment with a list `- [ ]` like I've started. Not really a music people, so I think linking to examples of each might be helpful also.

**Comment by pattyjogal** [comment]
Edited!

**Comment by goyney** [comment]
All of these, with the exception of the Alto clef, are in issue #3263. I'm going to edit this issue to be a request for the Alto clef.

**Comment by goyney** [comment]
Alto will now be added in #3263. Please follow that issue for status on when it has been added. Thanks!
