### ISSUE TITLE
A Few Aliases for Consideration

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1913]
- [x] **account-box-outline:** selfie-outline
- [x] **airplane-*:** aeroplane-*
- [x] **alert-circle-outline:** git-issue (#1059)
- [x] **alert-decagram:** new-releases
- [x] **arrow-collapse-*:** arrow-compress-*
- [x] **attachment:** paperclip-horizontal
- [x] **barley:** grain
- [x] **beach:** parasol
- [x] **bike:** bicycle,cycling
- [x] **book:** git-repository (#1059)
- [x] **brush:** paintbrush
- [x] **bullseye:** target
- [x] **camera:** photography
- [x] **cancel:** ban
- [x] **cellphone-*:** mobile-phone-\*, smartphone-*
- [x] **check-*:** tick-*
- [x] **coffee:** cup,tea
- [x] **coffee-outline:** cup-outline, tea-outline
- [x] **currency-eur:** euro
- [x] **currency-gbp:** pound,sterling
- [x] **currency-ngn:** naira
- [x] **currency-rub:** ruble
- [x] **currency-try:** lira
- [x] **currency-usd:** dollar
- [x] **currency-usd-off:** dollar-off
- [x] **delete:** bin
- [x] **delete-variant:** bin-variant
- [x] **dialpad:** keypad
- [x] **dice-*:** die-*
- [x] **dna:** helix
- [x] **do-not-disturb:** no-entry
- [x] **dots-*:** ellipsis-*
-  ~**earth:** planet~
- [x] **ferry:** boat, ship
- [x] **flash-outline:** lighning-bolt-outline
- [x] **flashlight:** torch
- [x] **flashlight-off:** torch-off
- [x] **format-superscript:** exponent
- [x] **gas-station:** gas-pump, petrol-pump, petrol-station
- [x] **gift:** present
- [x] **gondola:** cable-car
- [x] **highway:** motorway
- [x] **home-map-marker:** house-map-marker
- [x] **home-outline:** house-outline
- [x] **lightbulb:** idea
- [x] **lightbulb-on:** idea-on
- [x] **lightbulb-on-outline:** idea-on-outline
- [x] **lightbulb-outline:** idea-outline
- [x] **looks:** rainbow
- ~**mailbox:** postbox~
- [x] **marker:** highlighter (#1791)
-  ~**menu-*:** caret-*~
- [x] **message-alert:** feedback (#1912)
- [x] **motorbike:** motorcycle
- [x] **movie:** film
- [x] **needle:** syringe (#1761)
- [x] **paperclip:** attachment-vertical
- [x] **parking:** car-park ~,carpark~
- [x] **pharmacy:** chemist
- [x] **pillar:** column
- [x] **pine-tree:** forest
- [x] **pistol:** gun
- [x] **pizza:** pizzeria
- [x] **plane-shield:** aeroplane-shield, airplane-shield
- [x] **power-socket-*:** plug-socket-*
- [x] **rhombus:** diamond
- [x] **rhombus-outline:** diamond-outline
- [x] **run:** emergency-exit
- [x] **smoking:** cigarette,smoking-area
- [x] **smoking-off:** no-smoking~,smoke-free~
- [x] **stadium:** arena
- [x] **subway:** metro,tube,underground
- [x] **subway-variant:** metro-variant,tube-variant,underground-variant
- [x] **summit:** peak
- [x] **temperature-celsius:** temperature-centigrade
- [x] **tent:** camping
- [x] **theater:** cinema,theatre
- [x] **ticket-percent:** voucher
- [x] **timer:** stopwatch
- [x] **timer-off:** stopwatch-off
- [x] **truck:** lorry
- [x] **truck-delivery:** lorry-delivery
- [x] **truck-fast:** courier,lorry-fast
- [x] **tune:** equaliser
- [x] **tune-vertical:** equaliser-vertical
- [x] **vector-curve:** bezier (#1884)
- [x] **vk-box:** vkontakte-box
- [x] **vk-circle:** vkontakte-circle
- [x] **washing-machine:** laundrette

**Comment by JapanYoshi** [comment]
``subway`` can also be ``metro`` for Europe or ``tube`` for the UK.

**Comment by PeterShaggyNoble** [comment]
Thanks, @JapanYoshi, added those.

**Comment by PeterShaggyNoble** [comment]
Bumping this to remind myself to update it on Monday.

**Comment by GreenTurtwig** [comment]
Another addition for `subway` could be `underground` as it's another term we use in the UK.

**Comment by PeterShaggyNoble** [comment]
@GreenTurtwig: Already on the list.

**Comment by PeterShaggyNoble** [comment]
@Templarian, would you like me to keep this updated with *all* alias suggestions so we have them all in one list or will I just keep it updated with my own suggestions?

**Comment by PeterShaggyNoble** [comment]
Slightly more abstract but would `script` suit our needs?

[![](https://materialdesignicons.com/icon/script)](https://materialdesignicons.com/icon/script)
