### ISSUE TITLE
Planning for v2.0.xx

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#1983]
You know what would be fun, planning for `v2.0.xx` release.

While `1.9.32` was about renames/breaking changes. Ironically it's looking like the `v2.0.xx` should be a little less breaking.

Tasks

- [x] Naming fixes?
- [ ] Drop IE8 Support. `:before`, `::before`
- [ ] Only include WOFF, WOFF2, TTF (included not used).

Icons

- [ ] #180 - Calculator Icons
- [ ] #263 - Image Editor Selection Types
- [ ] #302 - Weight LB / g
- [ ] #393 - email-box & link-box
- [ ] #400 - Geometry
- [ ] #409 - Flickr
- [ ] #480 - piggybank
- [ ] #521 - chess icons (with `-outline` variants)
- [ ] #541 - Weather Icons - Review which are still needed
- [ ] #561 - library-video
- [ ] #1034 - GPU
- [ ] #1323 - hammer
- [ ] #1422 - Linux Distros
- [x] #1426 - EU Powersocket
- [ ] #1578 - Playing Card Suits
- [ ] #1858 - Starred List
- [ ] #1913 - A Few Aliases
- [ ] #1968 - Restore / reset icon

**Comment by MrGrigri** [comment]
I believe for issue #1422, we should only include the most common. And according to Distrowatch<sup>†</sup>, the top 10 for 2016 were: 

* Mint
* Debian
* Ubuntu
* OpenSUSE
* Manjaro
* Fedora
* Zorin
* elementary
* CentOS
* Arch 

And of corse, we must take into account those icons that will not look recognizable at a 24x24 size. 

<hr>

<sup>†</sup>: [Distrowatch](https://distrowatch.com/index.php?dataspan=2016)

**Comment by Templarian** [comment]
@MrGrigri / Others feel free to edit my comment to extend the list with bullet points.

**Comment by PeterShaggyNoble** [comment]
Added #521.

**Comment by Templarian** [comment]
If we drop IE8 support complete which kind of is the plan for the next version... I think we can drop all the other fonts.

Over on the official set @Pomax wrote a good write up [here](https://github.com/google/material-design-icons/issues/594) on why it's probably a good idea.

We're really going to be targeting Bootstrap v4 realistically going forward and even that is IE10+ (we'll have IE9+).

**Comment by Templarian** [comment]
He's right we could drop legacy mobile versions also and leave out ttf also. Need to look into that, unfortunately I don't have stats to see who still really uses that.

**Comment by JamesCoyle** [comment]
I use TTF to install as a system font.

**Comment by Templarian** [comment]
@JamesCoyle https://materialdesignicons.com/design You want the design download, not the webfont. This is released after every version also.

**Comment by JamesCoyle** [comment]
Ah so there's still a TTF available. I'm all for getting rid of the TTF webfont. Personally think it's time to abandon IE and anything before Android Lollipop (though best to support KitKat too).

**Comment by PeterShaggyNoble** [comment]
Anything that helps kill off IE gets my vote! 😆 

Personally, for the benefit of those who _do_ use it as a system font and may not be aware of the design resources page, I'd like to see the TTF still included in the download, even if it's not in the CSS.

**Comment by Pomax** [comment]
Note that in terms of official support, Microsoft only supports IE11 and Edge "latest". Both of these support WOFF. Due to EOL promises, IE11 will stay supported for as long as Windows 10 is, as that's the browser that it technically came with, but realistically you're looking at IE11 support until windows 7 goes out of support in 2020.

**Comment by Templarian** [comment]
Thanks @Pomax, looks like that will be the plan for the next release.

Will work to update the build scripts shortly to remove these fonts (still going to include the TTF file in the build since it's useful for devs, and I don't think they are the type to go and grab the large SVG design package).

Other than this, 2.0.xx has really no large changes that should affect users that are coming from `v1.9.32` or even `v1.8.36`. Users from `v1.7.22` might have a small hickup with a few icons and all the CSS updates, but nothing that can't be solved in a few minutes.

**Comment by Templarian** [comment]
Still working on the backlog, but there are 2000 icons in MDI currently. Still need to get more in before the next release.

**Comment by Templarian** [comment]
Going to be wrapping up several icons this week/weekend and doing a release. Probably going to rollover a lot of these to a new issue when that happens. It will be roughly `~2.0.20` version.

Just need to drop support for the legacy browsers.

**Comment by Templarian** [comment]
The icon count we're at right now is the release for `v2.0.46`, fixing a few issues due to the server migration in the build process. 😄

**Comment by Templarian** [comment]
https://materialdesignicons.com/cdn/2.0.46/

Doing some testing and will update the bower/npm shortly.

**Comment by Templarian** [comment]
NPM/Bower release is out for SVG 2.0.46: https://github.com/templarian/materialdesign-svg

Ran into a minor regression bug that prevented me from releasing yesterday. Will be releasing tomorrow, then back to adding tons of icons. 😓 😄

**Comment by Templarian** [comment]
By the way npm/bower were updated to 2.0.46.

Now we play the waiting game to see if anything broke. Building more rigorous automated testing, but might need to start putting in code review checks with others before releases.

https://cdn.materialdesignicons.com/2.0.46/
The svg directory will also be the repo for those needing the meta.json outside of the CDN.

Will update the website tomorrow with the new version numbers.

**Comment by Templarian** [comment]
Closing moving discussion over to #2280
