### ISSUE TITLE
Planning for 2.1.xx

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#2280]
Okay since 2.0.46 is released, we need to start planning the next release. There are enough contributions probably to get there, just need to start syncing them into the system.

- [ ] Drop IE8 Support. `:before`, `::before`
- [ ] Only include WOFF, WOFF2, TTF (included not used).

Issues

- [x] Replace `vine` with `venmo`
- [x] Update `glassdoor` icon
- [x] #2310 (Add stock `toc` icon)
- [ ] Close all issues labeled [`Stock Google Icon`](https://github.com/Templarian/MaterialDesign/labels/Stock%20Google%20Icon).
- [x] #1795 (replace `burst-mode` icon)
- [ ] Replace `case-sensitive-alt` (ref: [#1797](https://github.com/Templarian/MaterialDesign/issues/1797#issuecomment-276368756))
- [x] #2010 (add @kumvert as a contributor)
- [x] #2414 (update Atlassian icons)
- [ ] #2512 (replace one of the video camera icons)
- [x] #2566 (remove `readability`)
- [x] #2580 (clean up point data)
- [ ] #2591 (update brand icons)

**Comment by PeterShaggyNoble** [comment]
Added #1795 to the list.

**Comment by robcresswell** [comment]
Is there anything a new contributor can do to help push this along? It would be great to see a new official release of the library; really appreciate all the hard work going into it.

**Comment by Templarian** [comment]
@robcresswell Working on it right now, and trying to get it ready for this weekend. I've built out tooling for aliasing, tagging for contributors. So the team manages that now. Next will allow them to rename, modify icon data, and insert new icons.

Slowly opening up more functionality, but it requires building out the tooling side.

**Comment by robcresswell** [comment]
That sounds awesome. I've been using this lib for a while for several projects, so I'm happy to help out if the learning curve isn't too much of a cliff edge 😛

**Comment by Templarian** [comment]
[MaterialDesignIcons.zip](https://github.com/Templarian/MaterialDesign/files/1529770/MaterialDesignIcons.zip)

Spent a while trying to upgrade the tools I was using, but ended up having to rollback a bunch, too many malformed icons that worked previously. I think we'll need to update this release without the latest build tools until we can update the incompatible path data (way more picky with the new font build).

**Comment by Templarian** [comment]
`v2.1.19` went out tonight.
