### ISSUE TITLE
Construction and gardening tools

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [Templarian/MaterialDesign#2366]
I'm struggling looking for an icon to represent a "build" process and I realized there are almost no icons related to creating things or building things, no real tool icons like a hammer etc.  The only one I could find is a wrench.

You need some icons representing build, generate, create, construction equipment and tools, saw, hammer etc.

- [x] hand saw (manual) (see #3920)
- [x] saw (electric circular) (see #3920)
- [x] hammer (duplicate of #1323)
- [x] bulldozer
- [x] culinary mixer
- [x] crane
- [ ] crossed wrench screwdriver (see #574)
- [x] [shovel](https://materialdesignicons.com/icon/shovel)
- [x] spade
- [ ] wheelbarrow
- [x] axe
- [ ] swiss army knife
- [ ] pliers
- [ ] trowel (see #3157)
- [ ] any icons that connote "build" or "create" or "generate"

**Comment by Templarian** [comment]
Can you include some example images/icons and the team can work on adding these (edited your issue to have a list).

**Comment by augustin32** [comment]
Hand Saw
![handsaw24](https://user-images.githubusercontent.com/14167196/31064254-391c7e62-a743-11e7-8609-b381ef826e0b.png)
![handsaw36](https://user-images.githubusercontent.com/14167196/31064255-3a98dd26-a743-11e7-939b-e2c2d079b311.png)
![handsaw48](https://user-images.githubusercontent.com/14167196/31064256-3bfd7ca8-a743-11e7-9760-531126d3cc2e.png)
Circular Saw
![circular-saw24](https://user-images.githubusercontent.com/14167196/31064262-3e84c1de-a743-11e7-9beb-ae8ac014a183.png)
![circular-saw36](https://user-images.githubusercontent.com/14167196/31064266-413a23f6-a743-11e7-81a1-9efa6f07cf13.png)
![circular-saw48](https://user-images.githubusercontent.com/14167196/31064268-42e31c08-a743-11e7-92ef-2c99a0363e4a.png)
Circular Saw Blade
![circular-saw-blade24](https://user-images.githubusercontent.com/14167196/31064281-5e2f29fc-a743-11e7-8044-a1d9ecbdb70d.png)
![circular-saw-blade36](https://user-images.githubusercontent.com/14167196/31064284-64990a1a-a743-11e7-993d-50f52e877736.png)
![circular-saw-blade48](https://user-images.githubusercontent.com/14167196/31064286-68cab11a-a743-11e7-8a1a-55bcf972d998.png)
[icons.zip](https://github.com/Templarian/MaterialDesign/files/1347907/icons.zip)

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/32164559-d128934c-bd57-11e7-9433-73f6c3d69a3a.png)
![image](https://user-images.githubusercontent.com/15905797/32164599-e6c153e2-bd57-11e7-962b-053263746229.png)
[spade.zip](https://github.com/Templarian/MaterialDesign/files/1426703/spade.zip)

**Comment by Louistwee** [comment]
![image](https://user-images.githubusercontent.com/27563848/44877824-6c382400-aca5-11e8-9858-7c8f4a459e7e.png)
Path:
``M 4,4.999672 c -0.5522847,0 -1,0.4477153 -1,1 v 4 1 c -0.4578817,4.53e-4 -0.8569625,0.311833 -0.96875,0.755859 v 3.216797 H 2.2871094 C 2.647753,14.369908 3.2978799,14.000762 4,13.999672 h 9 c 0.702112,10e-4 1.352346,0.370256 1.713,0.972656 h 1.318625 l -0.02344,-2.972656 h -0.0078 c 0,-0.552285 -0.448404,-0.972426 -1,-1 H 13 v -2 c 0,-0.5522847 -0.447715,-1 -1,-1 -0.552285,0 -1,0.4477153 -1,1 v 2 H 9 v -5 c 0,-0.5522847 -0.4477153,-1 -1,-1 z m 1,2 h 2 v 3 1 1 H 5 v -1 z M 17,11 v 8 h 5 V 18 L 19,17 18,11 Z M 4,15 c -1.1045695,0 -2,0.89543 -2,2 0,1.10457 0.8954305,2 2,2 h 9 c 1.104569,0 2,-0.89543 2,-2 0,-1.10457 -0.895431,-2 -2,-2 z``

**Comment by MrGrigri** [comment]
Tracking Bulldozer at #3438

**Comment by CoDEmanX** [comment]
The saws could use some bigger teeth

**Comment by Templarian** [comment]
Added `spade` and `circular-saw`. Going to close this as we can track the rest in separate issues.

**Comment by PeterShaggyNoble** [comment]
I've created new issues for the 3 outstanding icons.

@WhatFreshHellIsThis, if there are any other icons you would like added, please create a new issue for each.
