### ISSUE TITLE
Brand Icon Updates

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2591]
The following brand icons are in need of an update.
## Update
- [ ] `apple-finder` - See #2960
- [x] `bitbucket` - See #2414.
- ~~[`facebook-box`](https://github.com/Templarian/MaterialDesign/files/1475172/post-facebook.zip)~~ (*Ours adheres to Facebook's guidelines*)
- [ ] [`flattr`](https://github.com/Templarian/MaterialDesign/files/1461410/flattr.zip) - SVG font [here](https://flattr.com/fonts/flattr-icons.svg) - See #2961
- [ ] [`google-earth`](https://github.com/Templarian/MaterialDesign/files/1475146/earth.zip) - See #2962
- [ ] [`google-glass`](https://github.com/Templarian/MaterialDesign/files/1461537/glass.zip) - See #2963
- [ ] [`google-maps`](https://github.com/Templarian/MaterialDesign/files/1475166/maps.zip) - See #2964
- ~~[`google-pages`](https://github.com/Templarian/MaterialDesign/files/1461948/sites.zip) - They still use the old one in places to represent brand accounts.~~ (*I misremembered!*)
- [ ] [`google-photos`](https://github.com/Templarian/MaterialDesign/files/1475167/photos.zip) - See #2965
- [ ] [`google-plus-box`](https://github.com/Templarian/MaterialDesign/files/1475178/post-gplus.zip)
- [ ] [`google-translate`](https://github.com/google/material-design-icons/blob/master/action/svg/production/ic_g_translate_24px.svg) - See #2492.
- [ ] [`houzz` & `houzz-box`](https://www.houzz.com/logoGuidelines)
- [x] [`humble-bundle`](https://humblebundle-a.akamaihd.net/static/hashed/ed07bcc932d64a94f69c405c09514ad91af079b3.svg)
- [ ] `itunes` - They now use a [star](https://images.apple.com/v/music/f/images/overview/icons/itunes_dark_large.svg) to represent the iTunes brand while using the [note](https://images.apple.com/v/music/f/images/overview/icons/apple_music_dark_large.svg) for the iTunes programme (with `circle-outline`) and Apple Music (with `box`).
- [x] `jira` - See #2414.
- [x] [`jsfiddle`](https://github.com/Templarian/MaterialDesign/files/1475150/jsfiddle.zip)
- [x] `linux` - See #2940
- [x] `minecraft` - It's just a cube now but it does rely on colour. *// Not changing this one*
- [ ] [`opera`](https://dev.opera.com/images/logo.svg)
- [ ] `pandora`
- [ ] [`pinterest`](https://github.com/Templarian/MaterialDesign/files/1457950/pinterest.zip) - And `pinterest-box`. (The current version matches Google's one)
- [ ] `pocket`
- [ ] `steam`
- [x] `trello` - See #2414.
- [ ] `vk`, `vk-box` & `vk-circle`
- [ ] `wunderlist`
- [x] [`youtube-creator-studio`](https://github.com/Templarian/MaterialDesign/files/1475181/youtube-creator.zip)
- [ ] [`youtube-play`](https://github.com/Templarian/MaterialDesign/files/1475179/video-youtube.zip) - See #2317

## Rename (and alias with old names)
- [ ] `amazon-clouddrive` -> `amazon-drive`
- [ ] `apple-mobileme` -> `apple-icloud`
- [ ] `file-pdf` -> `file-acrobat`
- [ ] `file-pdf-box` -> `file-acrobat-box` (or `acrobat-box`, or just `acrobat`)
- [ ] `google-glass` -> `glass`
- ~~`google-pages` -> `google-sites`~~
- [ ] `hangouts` -> `google-hangouts`
- [ ] `stackexchange` -> `stack-exchange`
- [x] `stackoverflow` -> `stack-overflow` - See the last section in [their trademark guidelines](https://stackexchange.com/legal/trademark-guidance).
- [ ] `youtube-play` -> `youtube`

## Reassign
- [ ] `humble-bundle` -> @GreenTurtwig  - See below.
- [ ] `jsfiddle` -> Google
- [x] `medium` -> @Templarian - See #2340.
- [x] `mixer` -> @GreenTurtwig - See #2111.

## Remove
- [ ] `google-wallet`
- [x] `rdio`
- [x] `readability` - See #2566.

**Comment by Templarian** [comment]
Agree with all these changes, but I think we should be attributing all logos/brands to the generic contributor account.

**Comment by PeterShaggyNoble** [comment]
Couldn't decide whether to put `linux` on the list to be redesigned or just to renamed as `penguin`. It doesn't look too much like Tux and I know it's tough to fit Tux into a small icon.

Assigning the brand icons to the generic account might still give the impression that they were created by the community, which I assume is what you want to get away from, so would it make sense to create a new dummy contributor account to assign them to?

**Comment by PeterShaggyNoble** [comment]
Added a few icons from the extended set to the list.

**Comment by GreenTurtwig** [comment]
Odd that they use a star for iTunes on iOS 11, they still use the note for the desktop.

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/33013981-ac26de0a-cddd-11e7-9280-c7200918ef36.png)](https://github.com/Templarian/MaterialDesign/files/1487257/humble-bundle.zip)

**Comment by PeterShaggyNoble** [comment]
Added `google-wallet` to the list of icons to be removed as it, and Android Pay, have been replaced with Google Pay.

**Comment by PeterShaggyNoble** [comment]
Added `houzz` to the list of icons to be updated.

**Comment by PeterShaggyNoble** [comment]
Closing here as individual issues are being created for each to help us track them better.
