### ISSUE TITLE
Planning for 2.3.xx

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#2955]
- [x] `lock-question` and `lock-alert` #672
- [x] NAS device #2913 
- [x] `folder-edit` #793
- [x] `playlist-edit` #842
- [x] `scanner-off` #1099
- [x] `amazon-alexa` #1234
- [ ] `police` #1343
- [x] `car-limousine` #1369
- [x] `cellphone-message` #1551
- [x] `tumble-dryer` #1625
- [x] `steering-off` #1688
- [x] Various light icons #1712
- [x] Rename `nest-thermostat` to `thermostat` #2880
- [x] Linux distributions? #1422
- [ ] Folder icons? #1240
- [x] IEC/IEEE Power Statuses #2304
- [x] `chart-multiline` #2172
- [ ] `balloon` #1534

## Update brand icons
- [ ] `apple-finder` #2960
- [x] `flattr` #2961
- [x] `google-earth` #2962
- [ ] `google-glass` #2963
- [x] `google-maps` #2964
- [x] `google-photos` #2965
- [x] `google-translate` #2492
- [x] `houzz` & `houzz-box` #2972
- [x] `opera` #2974
- [x] `pandora` #2975
- [x] `pinterest` & `pinterest-box` #2976
- [x] `pocket` #2977
- [x] `steam` #2978
- [x] `vk`, `vk-box` & `vk-circle` #2979
- [x] `youtube-play` #2317

**Comment by Templarian** [comment]
http://templarian.com/2018/04/18/material-design-icons-v2-3-50/

Done! 24 days later and so many issues closed in this milestone.
