### ISSUE TITLE
New weather icons

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3736]
This issue is a combination of #541 and #1318.

We would like to rename the following icons:
- [ ] `weather-partlycloudy` => `weather-partly-cloudy`

We would like to add the following new icons to the library:
- [ ] `weather-snowy-heavy`(#3735)
- [ ] `weather-partly-rainy` (#3735)
- [ ] `weather-partly-snowy-rainy` (#3735)
- [ ] `weather-partly-snowy` (#3735)
- [ ] `weather-partly-lightning`  (#3735)
- [x] `weather-haze` (#541)
- [ ] `weather-hot` (#541)
- [ ] `weather-cloudy-alert` (#541)
- [ ] `weather-night-partly-cloudy`(#541)
- [x] `weather-tornado` (#541)
- [x] `snowflake-variation` (#541)

---

Several contributions were attached to both original issues:
- #1318 - Contributions originally by @adbstyle - [1318 Contributions.zip](https://github.com/Templarian/MaterialDesign/files/2614118/3735.Contributions.zip)
- #541 - Contributions originally by @SaltySeaDog - [541 Contributions.zip](https://github.com/Templarian/MaterialDesign/files/2614123/541.Contributions.zip)

---

All original contributions need some work to fit the current style of the weather icons currently included in the library.

**Comment by goyney** [comment]
**New "Partly" Variations**

![image](https://user-images.githubusercontent.com/1015040/49025769-59c96b80-f16a-11e8-90cd-5cabb423f6e8.png)![image](https://user-images.githubusercontent.com/1015040/49026002-d3615980-f16a-11e8-9290-820a411cc400.png)
![image](https://user-images.githubusercontent.com/1015040/49026092-fbe95380-f16a-11e8-8144-ab886069b818.png)![image](https://user-images.githubusercontent.com/1015040/49025826-72d21c80-f16a-11e8-87d5-0bd27c5c19e0.png)
![image](https://user-images.githubusercontent.com/1015040/49026312-8af66b80-f16b-11e8-8de2-d444a4802a2b.png)

---

For the rename of `weather-partlycloudy` to `weather-partly-cloudy`, I am proposing we also shift the icon up 1dp to make room for the other modifiers, without having the icon shift position when changing. I know this icon wouldn't be used for a "hover" state, but weather changes when using these icons would have an unwanted shift up that would be less than ideal:
![image](https://user-images.githubusercontent.com/1015040/49025726-474f3200-f16a-11e8-8ed9-1fbeafe28076.png)

---

**New weather conditions**

![image](https://user-images.githubusercontent.com/1015040/49026194-39e67780-f16b-11e8-8602-ad6c553c65a1.png)![image](https://user-images.githubusercontent.com/1015040/49026275-731ee780-f16b-11e8-8691-964cbc12a580.png)
![image](https://user-images.githubusercontent.com/1015040/49026327-99448780-f16b-11e8-8951-a3d23d812dff.png)

---

**Weather alerts**

![image](https://user-images.githubusercontent.com/1015040/49026379-bb3e0a00-f16b-11e8-9983-466785f9c32e.png)

Two options here: (I think I prefer the second)
![image](https://user-images.githubusercontent.com/1015040/49026399-c7c26280-f16b-11e8-957e-80021965b7ba.png)![image](https://user-images.githubusercontent.com/1015040/49026407-cee97080-f16b-11e8-8cd3-ad6ab01f94eb.png)

---

New snowflake:
![image](https://user-images.githubusercontent.com/1015040/49026481-f9d3c480-f16b-11e8-927e-431bc7c9fbb2.png)

---

Source for all icons in this issue: [weather.zip](https://github.com/Templarian/MaterialDesign/files/2616387/weather.zip)

**Comment by MrGrigri** [comment]
I like the `weather-sunny-alert-2`.

**Comment by PeterShaggyNoble** [comment]
Agreed on `weather-sunny-alert`; I initially saw a `H` in the sun of the first one before reading the name, although it's definitely clearer at the smaller size.

Added the `Alias` tag as we'll need to alias some of these, as well as some existing ones.

**Comment by goyney** [comment]
The star is a bit excessive, IMO. Material states to use as little detail as needed to convey the icon. Additionally, the rest of the weather icons use round terminators, so the moon doesn't match.

I do like the size of your moon better. See if you can address those comments and post back here. Use http://dev.materialdesignicons.com/contribute/github to generate your preview so we can see it at native resolution as well.

**Comment by terpro** [comment]
I rounded it off. I think the star adds a lot to show nighttime, and the weather-night icon also has stars.
![weather-night-partly-cloudy](https://user-images.githubusercontent.com/11605395/50745281-27397680-11de-11e9-93d5-20d38c305e45.png)
![weather-night-partly-cloudy](https://user-images.githubusercontent.com/11605395/50745297-40dabe00-11de-11e9-932d-a8b1477411bc.png)
[cloudy_night_nostar.svg](https://github.com/terpro/riderapp/blob/master/dev/icons/custom/cloudy_night_nostar.svg)
[cloudy_night.svg](https://github.com/terpro/riderapp/blob/master/dev/icons/custom/cloudy_night.svg)

**Comment by boehan** [comment]
I really like the `weather-night-partly-cloudy` by @terreng (with the star). It looks much better than the crescent moon. But if this one gets added, I would go for a changed `weather-night` icon as well, using @terreng's variant of the moon, for consistency reasons (maybe adding another star).

**Comment by Templarian** [comment]
Added all of these. But Agreed @terreng's is nicer but the download link no longer works (why we usually ask to attach zip files to comments).

I can overwrite the current one if we get the file for this. 😃

**Comment by terreng** [comment]
@Templarian My apologies, I linked to a repository which is now private. I made some adjustments to the star, heres the svg: [cloudy_night.svg](https://github.com/terreng/samples/blob/master/cloudy_night.svg)
And without a star: [cloudy_night_nostar.svg](https://github.com/terreng/samples/blob/master/cloudy_night_nostar.svg)

In a previous comment on some other issue you mentioned a contributor account once I have 5 icons. This would make 10. If it would allow me to edit my profile on the website that would be great. Thanks!
