### ISSUE TITLE
add all missing file outline versions

### ISSUE THREAD

**Issue by terreng** [Templarian/MaterialDesign#3964]
The majority of the file-* icons are missing an outlined version
- [x] file-account-outline
- [x] file-chart-outline
- [x] file-check-outline
- [x] file-cloud-outline
- [x] file-excel-outline
- [x] file-excel-box-outline
- [x] file-export-outline
- [x] file-import-outline
- [x] file-lock-outline
- [x] file-move-outline
- [x] file-multiple-outline
- [x] file-percent-outline
- [x] ~file-plus-outline~
- [x] file-powerpoint-outline
- [x] file-powerpoint-box-outline
- [x] file-question-outline
- [x] file-remove-outline
- [x] file-restore-outline
- [x] file-send-outline
- [x] file-undo-outline
- [x] file-word-outline
- [x] file-word-box-outline
- [x] file-xml-outline

The following already have open issues:

- [x] file-image-outline (#3956)
- [x] file-music-outline (#3959)
- [x] file-pdf-outline (#3958)
- [x] file-delimited-outline (#3960)
- [x] file-pdf-box-outline (#3101)

I have created outlined versions for those that don't already have open issues:

[![image](https://user-images.githubusercontent.com/11605395/53699024-bdca8400-3d98-11e9-8d78-a84fcf973e9e.png)](https://github.com/terreng/samples/blob/master/file-account-outline.svg)[![image](https://user-images.githubusercontent.com/11605395/53699058-1e59c100-3d99-11e9-86d0-226bd12ddcb1.png)](https://github.com/terreng/samples/blob/master/file-chart-outline.svg)
[![image](https://user-images.githubusercontent.com/11605395/53699074-4f39f600-3d99-11e9-9a02-f306a2ee9a38.png)](https://github.com/terreng/samples/blob/master/file-check-outline.svg)[![image](https://user-images.githubusercontent.com/11605395/53699087-5eb93f00-3d99-11e9-8860-b57dbe2eaa85.png)](https://github.com/terreng/samples/blob/master/file-cloud-outline.svg)
[![image](https://user-images.githubusercontent.com/11605395/53699094-85777580-3d99-11e9-9678-aea0ff92c3ac.png)](https://github.com/terreng/samples/blob/master/file-excel-outline.svg)[![image](https://user-images.githubusercontent.com/11605395/53699102-97591880-3d99-11e9-9bf4-54673a44defe.png)](https://github.com/terreng/samples/blob/master/file-excel-box-outline.svg)
[![image](https://user-images.githubusercontent.com/11605395/53699117-c2dc0300-3d99-11e9-9431-c9e8b8ce29b0.png)](https://github.com/terreng/samples/blob/master/file-export-outline.svg)[![image](https://user-images.githubusercontent.com/11605395/53699133-f028b100-3d99-11e9-8dfc-528f4d7cac89.png)](https://github.com/terreng/samples/blob/master/file-import-outline.svg)
[![image](https://user-images.githubusercontent.com/11605395/53699138-0cc4e900-3d9a-11e9-8189-cc6d024e03ed.png)](https://github.com/terreng/samples/blob/master/file-lock-outline.svg)[![image](https://user-images.githubusercontent.com/11605395/53699144-20704f80-3d9a-11e9-8ee7-b358ce55987d.png)](https://github.com/terreng/samples/blob/master/file-move-outline.svg)
[![image](https://user-images.githubusercontent.com/11605395/53699157-39790080-3d9a-11e9-849b-7f2c12c83db7.png)](https://github.com/terreng/samples/blob/master/file-multiple-outline.svg)[![image](https://user-images.githubusercontent.com/11605395/53699181-6a593580-3d9a-11e9-98e3-ab8f267abc5d.png)](https://github.com/terreng/samples/blob/master/file-pdf-box-outline.svg)
[![image](https://user-images.githubusercontent.com/11605395/53699189-7b09ab80-3d9a-11e9-9ed6-ce286516fd83.png)](https://github.com/terreng/samples/blob/master/file-percent-outline.svg)[![image](https://user-images.githubusercontent.com/11605395/53699194-8957c780-3d9a-11e9-922b-f485b1955612.png)](https://github.com/terreng/samples/blob/master/file-plus-outline.svg)
[![image](https://user-images.githubusercontent.com/11605395/53699211-abe9e080-3d9a-11e9-9f8b-91d0ae901053.png)](https://github.com/terreng/samples/blob/master/file-powerpoint-outline.svg)[![image](https://user-images.githubusercontent.com/11605395/53699216-bf954700-3d9a-11e9-9b60-0ef9d800068a.png)](https://github.com/terreng/samples/blob/master/file-powerpoint-box-outline.svg)
[![image](https://user-images.githubusercontent.com/11605395/53699228-e18ec980-3d9a-11e9-9952-91d96aa359a8.png)](https://github.com/terreng/samples/blob/master/file-question-outline.svg)[![image](https://user-images.githubusercontent.com/11605395/53699231-f0757c00-3d9a-11e9-83cc-c381189f3c3b.png)](https://github.com/terreng/samples/blob/master/file-remove-outline.svg)
[![image](https://user-images.githubusercontent.com/11605395/53699242-1438c200-3d9b-11e9-8065-47b5dae8f644.png)](https://github.com/terreng/samples/blob/master/file-restore-outline.svg)[![image](https://user-images.githubusercontent.com/11605395/53699248-2286de00-3d9b-11e9-8d73-4a5f4932ce38.png)](https://github.com/terreng/samples/blob/master/file-send-outline.svg)
[![image](https://user-images.githubusercontent.com/11605395/53699264-3a5e6200-3d9b-11e9-9f83-7b6f28c29349.png)](https://github.com/terreng/samples/blob/master/file-undo-outline.svg)[![image](https://user-images.githubusercontent.com/11605395/53699274-49451480-3d9b-11e9-93ee-230598389b85.png)](https://github.com/terreng/samples/blob/master/file-word-outline.svg)
[![image](https://user-images.githubusercontent.com/11605395/53699288-624dc580-3d9b-11e9-8bd1-37b811cec5cc.png)](https://github.com/terreng/samples/blob/master/file-word-box-outline.svg)[![image](https://user-images.githubusercontent.com/11605395/53699296-742f6880-3d9b-11e9-91e6-5c1b32af5579.png)](https://github.com/terreng/samples/blob/master/file-xml-outline.svg)

[file-outline.zip](https://github.com/terreng/samples/blob/master/file-outline.zip)

**Comment by goyney** [comment]
@terreng Nice work!

`file-pdf-box-outline` has already been created and is being tracked in #3101.

I have a couple of comments that may help improve some of them.

I think we should always try to respect the 2dp rule. Most of these have only 1dp of spacing between the outline of the file and the symbol. In some cases, it may be impossible to do that, but in any case that we can, I think we should adjust them.

Also, I noticed a few of them aren't very well aligned to the grid (see `file-export-outline`). See if you can better align them to the grid. By keeping them on the grid, they don't "fuzz" up at lower resolutions or smaller sizes.

Thanks for doing all these!

**Comment by terreng** [comment]
Some of these icons are ready to go, including file-multiple-outline and file-move-outline, because they are the exact same icon and placement just with an outline.

I didn't originally align the arrows in file-export-outline and file-import-outline because they weren't aligned in the filled version. Here I have aligned them:

[![image](https://user-images.githubusercontent.com/11605395/53749347-09923180-3e5c-11e9-8394-49ae7c2c046f.png)](https://github.com/terreng/samples/blob/master/file-export-outline-2.svg)[![image](https://user-images.githubusercontent.com/11605395/53749331-00a16000-3e5c-11e9-8ac2-726d7d69419d.png)](https://github.com/terreng/samples/blob/master/file-import-outline-2.svg)

I personally think it makes more sense to have a 1dp margin on the outlined versions so that the graphic's size stays consistent between the filled and outlined versions. I think the graphic ends up looking small and squished with 2dp margins. I'll let you decide which you prefer:

[![image](https://user-images.githubusercontent.com/11605395/53749837-2713cb00-3e5d-11e9-9ffc-ed435c032404.png)](https://github.com/terreng/samples/blob/master/file-account-outline-2.svg)[![image](https://user-images.githubusercontent.com/11605395/53749864-38f56e00-3e5d-11e9-952a-18516203fbf1.png)](https://github.com/terreng/samples/blob/master/file-chart-outline-2.svg)
[![image](https://user-images.githubusercontent.com/11605395/53749902-4f9bc500-3e5d-11e9-9160-7aa87586f527.png)](https://github.com/terreng/samples/blob/master/file-cloud-outline-2.svg)[![image](https://user-images.githubusercontent.com/11605395/53749957-6a6e3980-3e5d-11e9-99c2-bf175a2bdb2e.png)](https://github.com/terreng/samples/blob/master/file-lock-outline-2.svg)
[![image](https://user-images.githubusercontent.com/11605395/53750001-88d43500-3e5d-11e9-9258-6e75cfda4f71.png)](https://github.com/terreng/samples/blob/master/file-percent-outline-2.svg)[![image](https://user-images.githubusercontent.com/11605395/53750049-a86b5d80-3e5d-11e9-9b33-3fd41caabc51.png)](https://github.com/terreng/samples/blob/master/file-question-outline-2.svg)
[![image](https://user-images.githubusercontent.com/11605395/53750105-cb960d00-3e5d-11e9-9bec-444ab28319fc.png)](https://github.com/terreng/samples/blob/master/file-send-outline-2.svg)[![image](https://user-images.githubusercontent.com/11605395/53750131-dea8dd00-3e5d-11e9-9b9a-2e9b938b3c69.png)](https://github.com/terreng/samples/blob/master/file-undo-outline-2.svg)
[![image](https://user-images.githubusercontent.com/11605395/53750187-f5e7ca80-3e5d-11e9-9615-1a647d757e5f.png)](https://github.com/terreng/samples/blob/master/file-xml-outline-2.svg)

The file-plus-outline icon could go one of two ways:

[![image](https://user-images.githubusercontent.com/11605395/53751708-c20ea400-3e61-11e9-9ebe-7b27944c147d.png)](https://github.com/terreng/samples/blob/master/file-plus-outline-2.svg)[![image](https://user-images.githubusercontent.com/11605395/53751735-cdfa6600-3e61-11e9-81d2-e8c4f40e968a.png)](https://github.com/terreng/samples/blob/master/file-plus-outline-3.svg)


Here I have fixed alignment for a few icons and kept the 1dp margin:

[![image](https://user-images.githubusercontent.com/11605395/53750557-f765c280-3e5e-11e9-8838-49322abe6e8f.png)](https://github.com/terreng/samples/blob/master/file-remove-outline-2.svg)[![image](https://user-images.githubusercontent.com/11605395/53750595-0cdaec80-3e5f-11e9-8223-652ffbb72190.png)](https://github.com/terreng/samples/blob/master/file-word-outline-2.svg)

And now with a 2dp margin. I think the ms office icon letters are too small:

[![image](https://user-images.githubusercontent.com/11605395/53750692-5c211d00-3e5f-11e9-9de8-102bf7497a5d.png)](https://github.com/terreng/samples/blob/master/file-remove-outline-3.svg)[![image](https://user-images.githubusercontent.com/11605395/53750740-74913780-3e5f-11e9-9bc8-25cfc4f859ca.png)](https://github.com/terreng/samples/blob/master/file-word-outline-3.svg)
[![image](https://user-images.githubusercontent.com/11605395/53750833-ae623e00-3e5f-11e9-91cb-92ea26c0681c.png)](https://github.com/terreng/samples/blob/master/file-powerpoint-outline-2.svg)[![image](https://user-images.githubusercontent.com/11605395/53751044-38120b80-3e60-11e9-89f7-7b456d20c24e.png)](https://github.com/terreng/samples/blob/master/file-excel-outline-2.svg)

I have left file-word-box-outline and file-restore-outline as is because I think they're fine. 

[file-outline-2.zip](https://github.com/terreng/samples/blob/master/file-outline-2.zip)

**Comment by goyney** [comment]
All of these have been added! Thanks for all that work!
