### ISSUE TITLE
Add hulkhaugen as a Contributor

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4279]
- [x] Add @hulkhaugen as contributor
- [x] twitter
- [x] website
- [x] github
- [x] short bio (like 250 words max).

---

Icons to assign:

- [ ] led-strip-variant (#3836)
- [ ] floor-lamp-variant (#3836)
- [ ] floor-lamp-dual (#3836)
- [ ] coach-lamp (#3836)
- [ ] outdoor-lamp (#3836)

**Comment by goyney** [comment]
@hulkhaugen Please provide us with your twitter handle and website (if available) and a short bio so we can add you as a Contributor. 😄

**Comment by hulkhaugen** [comment]
Wow, thanks :)

My website and Twitter seems highly irrelevant for this, but if you want them:
https://twitter.com/BorreHaugen
https://bstart.net/

**Here's my shot at a bio:**
Offshore worker in the oil industry, coming from Arendal, Norway. My path went from electrician to ships electrician, to now being a ROV Supervisor. Since my mom bought an Olivetti 386 in my childhood, I knew that computers and I was going to spend a lot of time together. At one point, I made the step and replaced MSPaint with AutoCAD. I've always had OCD when it comes to visual details, consistency and alignments in UI's. I also like some programming, but can only claim to somewhat master HTML and CSS, my knowledge with Python and JavaScript is not at a level where I can confidently say "I know it" yet.

**Comment by Templarian** [comment]
Added the contributor account. We'll hopefully open up features eventually to work with the icon tooling to more. Until then please work through issue requests. 😃 

All icons should show up shortly attached. Thanks!

**Comment by goyney** [comment]
Thanks @Templarian. We'll get those 5 icons added at the tail end of `4.0` or the beginning of `4.1`. Just FYI, we're getting ready to released `3.9` and `4.0` is already queued up. 😄

**Comment by goyney** [comment]
Closing this since @hulkhaugen has been added. When #3836 is addressed, they'll be assigned to them. 👍
