### ISSUE TITLE
map-[hybrid, roadmap, terrain and  satellite]

### ISSUE THREAD

**Issue by fabriciojose** [Templarian/MaterialDesign#4598]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
This needs some examples. You can copy and paste images into an issue. We have general map/satellite icons.

**Comment by goyney** [comment]
Closing because the `Needs More Info` label was added several months ago without any followup. If you have some examples of what these icons might look like, please post them and we can reopen this issue for consideration. Thanks for your suggestion.
