### ISSUE TITLE
Brand Icon Review (February 2020)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4802]
With `v5` looming, it's as good a time as any for [another](https://github.com/Templarian/MaterialDesign/issues/2591) brand icon review. Fortunately, in my efforts to add all of our brand icons to [Simple Icons](https://simpleicons.org/), I've been through a good few of these already, which gives us a decent headstart.

If you find an outdated icon, please create a new issue for it for tracking purposes and edit the issue number into the list below. If an icon doesn't need to be updated or *has* been updated then check it off the list. If you don't have the necessary permissions to edit this post then leave a comment below and one of the team will do so.

- [x] `adobe`
- [x] `adobe-acrobat`
- [x] `airplay`
- [x] `amazon`
- [x] `amazon-alexa`
- [x] `amazon-drive` (#4818)
- [x] `android` (#4396)
- [x] `android-auto`
- [x] `android-debug-bridge`
- [x] `android-messages`
- [x] `android-studio`
- [x] `angular`
- [x] `angularjs`
- [x] `ansible`
- [x] `apache-kafka`
- [x] `apple`
- [x] `apple-finder`
- [x] `apple-icloud`
- [x] `apple-ios` (#4840)
- [x] `apple-safari`
- [x] `arch`
- [x] `artstation`
- [x] `atlassian`
- [x] `aws`
- [x] `azure`
- [x] `azure-devops`
- [x] `babel` (#4841)
- [x] `bandcamp`
- [x] `battlenet`
- [x] `bing`
- [x] `bitbucket`
- [x] `bitcoin`
- [x] `black-mesa`
- [x] `blender-software`
- [x] `blogger`
- [x] `bluetooth` (#4842)
- [x] `bootstrap`
- [x] `box`
- [x] `buffer`
- [x] `bulma` (#4704)
- [x] `centos`
- [x] `cisco-webex` (#4819)
- [x] `codepen`
- [x] `concourse-ci`
- [x] `cordova`
- [x] `creative-commons`
- [x] `cryengine`
- [x] `debian`
- [x] `dev-to`
- [x] `deviantart`
- [x] `digital-ocean` (#4551)
- [x] `discord`
- [x] `disqus`
- [x] `disqus-outline` (#4820)
- [x] `dlna`
- [x] `docker`
- [x] `dolby`
- [x] `dot-net`
- [x] `douban`
- [x] `dropbox`
- [x] `drupal`
- [x] `edge`
- [x] `edge-legacy`
- [x] `electron-framework`
- [x] `ember`
- [x] `emby`
- [x] `eslint`
- [x] `ethereum`
- [x] `evernote`
- [x] `facebook` (#4651)
- [x] `facebook-box` (#4821)
- [x] `facebook-messenger`
- [x] `facebook-workplace`
- [x] `fedora`
- [x] `firebase`
- [x] `firefox` (#4557)
- [x] `flickr` (#4822)
- [x] `font-awesome`
- [x] `freebsd`
- [x] `gatsby`
- [x] `gentoo`
- [x] `git`
- [x] `github-box` (#4823)
- [x] `github-circle` (#4823)
- [x] `github-face` (#4823)
- [x] `gitlab`
- [x] `gmail`
- [x] `gnome`
- [x] `gog`
- [x] `goodreads`
- [x] `google`
- [x] `google-adwords` (#4787)
- [x] `google-analytics`
- [x] `google-assistant`
- [x] `google-cardboard`
- [x] `google-chrome`
- [x] `google-classroom`
- [x] `google-cloud` (#4482)
- [x] `google-drive`
- [x] `google-earth`
- [x] `google-fit`
- [x] `google-glass` (#4824)
- [x] `google-hangouts`
- [x] `google-keep`
- [x] `google-lens`
- [x] `google-maps`
- [x] `google-my-business`
- [x] `google-nearby`
- [x] `google-pages` (#4825)
- [x] `google-photos`
- [x] `google-physical-web` (#4843)
- [x] `google-play`
- [x] `google-plus`
- [x] `google-plus-box` (#2971)
- [x] `google-podcast`
- [x] `google-spreadsheet`
- [x] `google-street-view`
- [x] `google-translate`
- [x] `graphql`
- [x] `hackernews` (#4844)
- [x] `home-assistant`
- [x] `hubspot`
- [x] `hulu`
- [x] `humble-bundle`
- [x] `instagram`
- [x] `internet-explorer`
- [x] `iobroker` (#4710)
- [x] `jabber`
- [x] `jira`
- [x] `jquery`
- [x] `jsfiddle`
- [x] `kickstarter`
- [x] `kodi`
- [x] `kotlin` (#4534)
- [x] `kubernetes`
- [x] `language-c`
- [x] `language-cpp`
- [x] `language-csharp`
- [x] `language-css3`
- [x] `language-fortran`
- [x] `language-go`
- [x] `language-haskell`
- [x] `language-html5`
- [x] `language-java`
- [x] `language-javascript`
- [x] `language-lua`
- [x] `language-php`
- [x] `language-python`
- [x] `language-python-text` (#4826)
- [x] `language-r`
- [x] `language-ruby-on-rails`
- [x] `language-swift`
- [x] `language-typescript`
- [x] `laravel` (#4364)
- [x] `lastpass`
- [x] `linkedin` (#4827)
- [x] `linkedin-box` (#4827)
- [x] `linux`
- [x] `linux-mint`
- [x] `litecoin`
- [x] `lumx`
- [x] `mapbox`
- [x] `markdown`
- [x] `markdown-outline`
- [x] `mastodon`
- [x] `mastodon-variant` (#4831)
- [x] `material-design`
- [x] `material-ui`
- [x] `meteor`
- [x] `microsoft`
- [x] `microsoft-dynamics`  (#4845)
- [x] `midi` (#4846)
- [x] `minecraft`
- [x] `mixer`
- [x] `nativescript`
- [x] `netflix`
- [x] `nfc` (#4788)
- [x] `nfc-off` (#4788)
- [x] `nintendo-switch`
- [x] `nix`
- [x] `nodejs`
- [x] `npm`
- [x] `npm-variant` (#4828)
- [x] `npm-variant-outline` (#4828)
- [x] `nuxt`
- [x] `oci` (#4711)
- [x] `odnoklassniki`
- [x] `office`
- [x] `onedrive`
- [x] `onenote` (#4847)
- [x] `onepassword`
- [x] `open-source-initiative`
- [x] `openid`
- [x] `opera`
- [x] `origin`
- [x] `outlook` (#4847)
- [x] `pandora`
- [x] `patreon`
- [x] `pi-hole`
- [x] `pinterest`
- [x] `pinterest-box` (#4832)
- [x] `playstation`
- [x] `plex`
- [x] `polymer`
- [x] `powershell`
- [x] `qi`
- [x] `qqchat`
- [x] `quora`
- [x] `react`
- [x] `reddit` (#4848)
- [x] `redhat`
- [x] `rollupjs`
- [x] `ruby`
- [x] `salesforce`
- [x] `sass`
- [x] `semantic-web` (#4510)
- [x] `simple-icons` (#4741)
- [x] `sina-weibo`
- [x] `skype`
- [x] `skype-business`
- [x] `slack`
- [x] `snapchat`
- [x] `soundcloud`
- [x] `spotify`
- [x] `stack-exchange`
- [x] `stack-overflow`
- [x] `stackpath` (#4650)
- [x] `steam`
- [x] `steam-box` (#4833)
- [x] `symfony`
- [x] `teamviewer`
- [x] `telegram`
- [x] `terraform`
- [x] `trello`
- [x] `twitch` (#4849)
- [x] `twitter`
- [x] `twitter-box` (#4834)
- [x] `twitter-circle` (#4834)
- [x] `ubisoft`
- [x] `ubuntu`
- [x] `umbraco`
- [x] `unicode` (#4851)
- [x] `unity`
- [x] `unreal`
- [x] `untappd`
- [x] `vimeo`
- [x] `visual-studio`
- [x] `visual-studio-code`
- [x] `vk` (#4835)
- [x] `vk-box` (#4835)
- [x] `vk-circle` (#4835)
- [x] `vlc`
- [x] `vuejs`
- [x] `vuetify`
- [x] `waze`
- [x] `webpack`
- [x] `webrtc` (#4543)
- [x] `wechat`
- [x] `whatsapp` (#4852)
- [x] `wii`
- [x] `wiiu`
- [x] `wikipedia`
- [x] `windows`
- [x] `windows-classic`
- [x] `wordpress`
- [x] `xamarin`
- [x] `xamarin-outline`
- [x] `xaml`
- [x] `xbox`
- [x] `xing` (#4836)
- [x] `xing-box`(#4836)
- [x] `xing-circle`(#4836)
- [x] `xmpp`
- [x] `yahoo` (#4730)
- [x] `yammer` (#4847)
- [x] `youtube`
- [x] `youtube-creator-studio` (#4853)
- [x] `youtube-gaming`
- [x] `youtube-tv`
- [x] `z-wave`
- [x] `zend`
- [x] `zigbee`

**Comment by goyney** [comment]
The only thing left here is to figure out what to do with `apple-ios`.

**Comment by Templarian** [comment]
Could update it with the thin font? Still think it's useful to include.

**Comment by goyney** [comment]
This issue is now complete.
