### ISSUE TITLE
"Food allergens and safety" icons

### ISSUE THREAD

**Issue by adityakahb** [Templarian/MaterialDesign#4954]
For platforms based on food, restaurants etc., Food-safety-allergens icons could be useful. So far I could see "Peanut" and "Peanut-off" related icons in the library.

I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

- While creating a recipe article or showing recipe to end-user.
- Restaurant menu and online-food ordering.

## Examples

https://www.123rf.com/photo_57363007_stock-vector-set-of-allergy-ingredient-warning-labels-common-allergens-icons-gluten-and-sulfite-sensitivity-celer.html?fromid=aUJWTUNmaUpUb05FR1ZLZHMwRXVWdz09

https://www.123rf.com/photo_55816913_stock-vector-allergen-icons-vector-set.html?fromid=RUZDbk1JaE5zYkNRWkZlcFRpUUlEUT09

**Comment by goyney** [comment]
Here's a list of everything from the two images (in no particular order):
- [x] Eggs - https://materialdesignicons.com/icon/egg
- [x] Citrus - https://materialdesignicons.com/icon/fruit-citrus
- [x] Corn - https://materialdesignicons.com/icon/corn
- [x] Gluten - https://materialdesignicons.com/icon/barley
- [ ] Chocolate
- [x] Fish - https://materialdesignicons.com/icon/fish
- [x] Dairy - https://materialdesignicons.com/icon/cheese
- [x] Soy - https://materialdesignicons.com/icon/soy-sauce
- [x] Cherry - https://materialdesignicons.com/icon/fruit-cherries
- [ ] Strawberry - #4491
- [x] Mushroom - https://materialdesignicons.com/icon/mushroom
- [ ] Celery
- [x] Trans Fat - https://materialdesignicons.com/icon/water
- [x] GMO - https://materialdesignicons.com/icon/flask
- [x] Nuts - https://materialdesignicons.com/icon/peanut
- [ ] Mustard
- [ ] Sugar
- [ ] Artificial Sweetener
- [ ] Seafood - #3780
- [x] Honey - https://materialdesignicons.com/icon/beehive-outline
- [ ] Sesame
- [ ] Lupins
- [ ] Meat
- [x] Artificial Color - https://materialdesignicons.com/icon/eyedropper
- [ ] Preservatives

We have a lot of these, and a few issues open as well. There are probably a few more we can add.

**Comment by goyney** [comment]
Not going to create previews for all of them, but here are a bunch of `off` variants of the icons we already have.
[food-off.zip](https://github.com/Templarian/MaterialDesign/files/4301825/food-off.zip)

**Comment by adityakahb** [comment]
Thanks @goyney

**Comment by goyney** [comment]
Alrighty, all of the `off` versions have been added. Here's what's left and my comments around each:

New additions with issues:
- [ ] Strawberry - Will be addressed in #4490
- [ ] Seafood - Will be addressed in #3780
- [ ] Chocolate - Created #4961 to address
- [ ] Meat - Created #4962 to address
- [ ] Mustard - Would a generic bottle work, such as the one requested in #4953?

Potential alternatives already included:
- [ ] Celery - Would `leak` work in this case?
- [ ] Sugar - Would `shaker(-outline)` work in this case?
- [ ] Artificial Sweetener - Would `shaker(-outline)` work in this case?
- [ ] Sesame - Would `seed(-outline)` work in this case?
- [ ] Lupins - Would any of our flower icons work?

- [x] Preservatives - The common icon I see for this is similar to the `flask` for GMO, so I'm going to count this one as fulfilled.

@adityakahb Could you respond to the "potential alternatives" section? If any of those work, we'll get `off` variants made for them as well.

**Comment by adityakahb** [comment]
@goyney Leek and Seed will work for Celery and Sesame respectively.

For Lupins, can we have an icon like `corn` with smaller leaves and adding pixel pattern like `braille` to it? https://www.pixtastock.com/photo/28440450

Shakers would be good for salt and pepper. So for sugar, following ideas could be better:
https://www.vecteezy.com/vector-art/564514-sugar-icon
https://www.pinclipart.com/maxpin/xRhihx/

**Comment by goyney** [comment]
We can't do cubes, perspective is not allowed in Material. 😞

**Comment by adityakahb** [comment]
Can we have an icon showing spoon loaded with plain cubes?

**Comment by Nanianmichaels** [comment]
> Can we have an icon showing spoon loaded with plain squares? I am out of ideas now.

A couple of random thoughts, not sure if these might help:

- The shaker icon, but with bigger, plain, squares, instead of the tiny ones available now?
- A "bigger stream" on the shaker, considering the amount of product each "shake" brings when it comes to sugar.
- A different "tip" for the shaker, thin and long instead of wide and short, for sugar.

**Comment by adityakahb** [comment]
> > Can we have an icon showing spoon loaded with plain squares? I am out of ideas now.
> 
> A couple of random thoughts, not sure if these might help:
> 
> * The shaker icon, but with bigger, plain, squares, instead of the tiny ones available now?
> * A "bigger stream" on the shaker, considering the amount of product each "shake" brings when it comes to sugar.
> * A different "tip" for the shaker, thin and long instead of wide and short, for sugar.

Thanks @Nanianmichaels . Usually, a shaker is associated with salt and pepper. Common term related to sugar is "A teaspoon full of". Though we have sugar shakers available in reality (https://www.amazon.com/Sugar-Shakers/b?ie=UTF8&node=3737081), I am not sure if shaker icon for sugar will be distinguishable easily.

**Comment by Nanianmichaels** [comment]
> I am not sure if shaker icon for sugar will be distinguishable easily.

Yeah, that is a potential issue. Sugar shakers are not common where I live, either, but if you can't have cubes, I'm not seeing many more options besides variations on shakers.
Of course, you could always add NaCl to the salt shaker, but then you'd get slammed by large amounts of people who don't know Sodium Chloride is table salt...

**Comment by adityakahb** [comment]
> > I am not sure if shaker icon for sugar will be distinguishable easily.
> 
> Yeah, that is a potential issue. Sugar shakers are not common where I live, either, but if you can't have cubes, I'm not seeing many more options besides variations on shakers.
> Of course, you could always add NaCl to the salt shaker, but then you'd get slammed by large amounts of people who don't know Sodium Chloride is table salt...

Hey @Nanianmichaels I am not against cubes. In fact, cubes seem to be the best option for Sugar. Actually I am not in favor of Shaker for Sugar. That is why I thought of a vector showing a spoon full of cubes. Please help in exploring more options.

**Comment by Nanianmichaels** [comment]
According to @goyney, we can't have cubes, so a spoon with cubes is apparently out of the question.

Not to mention sugar cubes are not universal (for instance, over here it's all individual packets, cubes are something you need to go out of your way to buy, if they're even available).

That being said, I just came across a couple of options:
https://www.123rf.com/photo_99323822_stock-vector-sugar-icon.html (no cubes, just squares, though I find that spoon too deep, personally)
https://www.istockphoto.com/pt/vetorial/sugar-icon-vector-illustration-gm922038588-253154179

Though I'm guessing the second one might not be an option if you can't use words (not sure on what the guidelines say on this).

**Comment by adityakahb** [comment]
@Nanianmichaels : Hey I really meant squares, when I said cubes. I think Sugar cane should definitely be our last option. Since the existing set has spoon and bowl icons already. Can we try adding squares around them to represent sugar?

https://www.google.com/imgres?imgurl=https%3A%2F%2Fimages.assetsdelivery.com%2Fcompings_v2%2Fbsd555%2Fbsd5551609%2Fbsd555160900467.jpg&imgrefurl=https%3A%2F%2Fen.clipdealer.com%2Fvector%2Fmedia%2FA%3A74630952&tbnid=NICpTzyrsbsR3M&vet=10CHIQMygzahcKEwiwnp7yivvoAhUAAAAAHQAAAAAQBA..i&docid=O-zVTys_i5lPBM&w=450&h=450&itg=1&q=sugar%20icon&ved=0CHIQMygzahcKEwiwnp7yivvoAhUAAAAAHQAAAAAQBA

https://www.google.com/imgres?imgurl=https%3A%2F%2Fpreviews.123rf.com%2Fimages%2Fcoolvectorstock%2Fcoolvectorstock1811%2Fcoolvectorstock181101690%2F114732972-sugar-in-a-bowl-transparent-icon-and-symbol-design.jpg&imgrefurl=https%3A%2F%2Fwww.123rf.com%2Fphoto_114732972_stock-vector-sugar-in-a-bowl-transparent-icon-and-symbol-design.html&tbnid=tvlbKykBGcTcFM&vet=12ahUKEwjFz-PWjPvoAhXDEXIKHbr8AH4QMygGegUIARCCAg..i&docid=XbgTbwAo0j2dwM&w=1300&h=1300&q=transparent%20sugar%20icon&hl=en-US&ved=2ahUKEwjFz-PWjPvoAhXDEXIKHbr8AH4QMygGegUIARCCAg

**Comment by goyney** [comment]
We've added `spoon-sugar`, but it doesn't lend itself to an `off` variant.
[![spoon-sugar](https://materialdesignicons.com/icon/spoon-sugar)](https://materialdesignicons.com/icon/spoon-sugar)

Therefore, we've created `cube-off-outline`, which is an `off` variant of an existing icon that already breaks Material guidelines that we made a special exception for at one point in time. I'm adding the sugar aliases to these icons as well.
[![cube-outline](https://materialdesignicons.com/icon/cube-outline)](https://materialdesignicons.com/icon/cube-outline)[![cube-off-outline](https://materialdesignicons.com/icon/cube-off-outline)](https://materialdesignicons.com/icon/cube-off-outline)

Considering all icons in this issue have been addressed or there are other open issues to deal with the remaining icons, I'm going to close this one.
