### ISSUE TITLE
Duplicated tags on icons in meta.json

### ISSUE THREAD

**Issue by Xcodo** [Templarian/MaterialDesign#5180]
I was parsing the [5.2.45 meta.json file](https://cdn.materialdesignicons.com/5.2.45/meta.json) for a C#/Xamarin Forms helper library I'm thinking of making and noticed some duplication in the tags on icons:

27 icons have duplicate tags.
- [x] Icon alpha-o-box-outline has a tag "Alpha / Numeric" repeated 3 times.
- [x] Icon alphabet-piqad has a tag "Alpha / Numeric" repeated 2 times.
- [x] Icon badge-account-alert has a tag "Alert / Error" repeated 2 times.
- [x] Icon border-bottom-variant has a tag "Text / Content / Format" repeated 2 times.
- [x] Icon chart-histogram has a tag "Math" repeated 2 times.
- [x] Icon content-save-settings-outline has a tag "Settings" repeated 2 times.
- [x] Icon cube-outline has a tag "Food / Drink" repeated 2 times.
- [x] Icon folder-alert has a tag "Alert / Error" repeated 3 times.
- [x] Icon food-apple has a tag "Food / Drink" repeated 2 times.
- [x] Icon map-marker-remove-variant has a tag "Geographic Information System" repeated 3 times.
- [x] Icon monitor-dashboard has a tag "Device / Tech" repeated 2 times.
- [x] Icon numeric-1-box-multiple has a tag "Alpha / Numeric" repeated 2 times.
- [x] Icon numeric-10-box has a tag "Alpha / Numeric" repeated 3 times.
- [x] Icon numeric-4-circle has a tag "Alpha / Numeric" repeated 2 times.
- [x] Icon numeric-5-box-multiple has a tag "Alpha / Numeric" repeated 2 times.
- [x] Icon numeric-5-circle has a tag "Alpha / Numeric" repeated 2 times.
- [x] Icon numeric-7-box-multiple-outline has a tag "Alpha / Numeric" repeated 2 times.
- [x] Icon numeric-8 has a tag "Alpha / Numeric" repeated 2 times.
- [x] Icon numeric-8-box has a tag "Alpha / Numeric" repeated 2 times.
- [x] Icon numeric-8-box-multiple-outline has a tag "Alpha / Numeric" repeated 2 times.
- [x] Icon numeric-9-box-multiple has a tag "Alpha / Numeric" repeated 2 times.
- [x] Icon numeric-9-box-multiple-outline has a tag "Alpha / Numeric" repeated 2 times.
- [x] Icon numeric-9-box-outline has a tag "Alpha / Numeric" repeated 2 times.
- [x] Icon road has a tag "Transportation + Road" repeated 2 times.
- [x] Icon video-3d has a tag "Video / Movie" repeated 2 times.
- [x] Icon watch-export-variant has a tag "Device / Tech" repeated 2 times.
- [x] Icon weather-night-partly-cloudy has a tag "Weather" repeated 2 times.

While I can deal with this, it doesn't seem ideal.

**Comment by Templarian** [comment]
Oh, I think these were added with the legacy alias/tag pages. I might have to finally deprecate these if any of the core team is still using them. That or fix the pages.

**Comment by Templarian** [comment]
Done. These will be fixed in 5.3.45 and the verify script will not let us publish with duplicate aliases/tags.

@Xcodo Thanks again for submitting such a detailed bug report. This helped a lot! 💯

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/82740195-21c5c900-9d0c-11ea-8593-3330de28e9d8.png)

Adding this to the build tooling with all the other checks. ✔️

**Comment by Xcodo** [comment]
Looks good! I do love build tooling, the challenge is thinking up the problems to check for. I did also do checks that all names, IDs and codepoints were unique in the JSON list.

**Comment by Templarian** [comment]
Perfect. We have verification for unique values, but good to double check. One oddity that got added for 5.0 was to also verify that if we remove the `-` hyphens the names are still unique since some convert these to enums without underscores.

Lot of third party repackaging going on after each release by various libs. 🥰 

@Xcodo Feel free to update the xamarin docs via a PR. Always open to alternative solutions especially if they don't package the entire icon pack or use the webfont. The current Xamarin implementation uses the webfont. 😨 

http://dev.materialdesignicons.com/getting-started/xamarin

**Comment by Xcodo** [comment]
@Templarian will do. They could do with an update as there's been some improvement in Xamarin Forms, but there's no SVG support so the webfont is still the way to go for mobile apps I think.

**Comment by Templarian** [comment]
@Xcodo 5.3.45 went out with these fixes.
