### ISSUE TITLE
RELEASED - Version 6.1.95 - Breaking Changes

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#5409]
**Version 6.1.95 was released on Monday, September 6th, 2021.**

---

We are now at the halfway point between v5 and v6, so I felt that it would be appropriate to have a single resource tracking all upcoming breaking changes that will be introduced in our v6 release. This issue will be kept updated as we get closer and closer to release and then will act as a reference.

## Icons Being Removed (41)
The follow icons have been deprecated and will be removed entirely:
- [x] `adobe` (#5797)
- [x] `adobe-acrobat` (#5797)
- [x] `amazon`
- [x] `amazon-alexa`
- [x] `android-auto`
- [x] `android-debug-bridge`
- [x] `bandcamp`
- [x] `battlenet`
- [x] `blogger`
- [x] `buffer`
- [x] `cash-usd` (#5661)
- [x] `cash-usd-outline` (#5661)
- [x] `cellphone-android` (#5276)
- [x] `cellphone-iphone` (#5276)
- [x] `concourse-ci`
- [x] `currency-usd-circle` (#5661)
- [x] `currency-usd-circle-outline` (#5661)
- [x] `do-not-disturb` (#5135)
- [x] `do-not-disturb-off` (#5135)
- [x] `douban`
- [x] `file-pdf` (#5797)
- [x] `file-pdf-outline` (#5797)
- [x] `file-pdf-box-outline` (#5797)
- [x] `google-photos` (#5293)
- [x] `home-currency-usd` (#5661)
- [x] `laptop-chromebook` (#5276)
- [x] `laptop-mac` (#5276)
- [x] `laptop-windows` (#5276)
- [x] `microsoft-edge-legacy`
- [x] `microsoft-yammer`
- [x] `pdf-box` (#5797)
- [x] `plus-one` (#5408)
- [x] `poll-box` (#5885)
- [x] `poll-box-outline` (#5885)
- [x] `tablet-ipad` (#5276)
- [x] `telegram` (#5275)
- [x] `untappd`
- [x] `vk`
- [x] `xamarian-outline`
- [x] `xing`
- [x] `y-combinator`

## Icons Being Renamed (51)
The following icons are being renamed:
- [x] `apple-airplay` ➜ `cast-variant` (#5376)
- [x] `application` ➜ `application-outline` (#6087)
- [x] `application-cog` ➜ `application-cog-outline` (#6087)
- [x] `application-settings` ➜ `application-settings-outline` (#6087)
- [x] `bolnisi-cross` ➜ `cross-bolnisi` (#5803)
- [x] `boom-gate-up` ➜ `boom-gate-arrow-up` (#6008)
- [x] `boom-gate-up-outline` ➜ `boom-gate-arrow-up-outline` (#6008)
- [x] `boom-gate-down`➜ `boom-gate-arrow-down` (#6008)
- [x] `boom-gate-down-outline` ➜ `boom-gate-arrow-down-outline` (#6008)
- [x] `buddhism` ➜ `dharmachakra` (#5541)
- [x] `cellphone-erase` ➜ `cellphone-remove` (#5874)
- [x] `celtic-cross` ➜ `cross-celtic` (#5803)
- [x] `check-box-multiple-outline`  ➜ `checkbox-multiple-outline` (#5914)
- [x] `check-box-outline`  ➜ `checkbox-outline` (#5914)
- [x] `christianity` ➜ `cross` (#5541)
- [x] `christianity-outline` ➜ `cross-outline` (#5541)
- [x] `face` ➜ `face-man` (#5675)
- [x] `face-outline` ➜ `face-man-outline` (#5675)
- [x] `face-profile` ➜ `face-man-profile` (#5675)
- [x] `face-profile-woman` ➜ `face-woman-profile` (#5675)
- [x] `face-shimmer` ➜ `face-man-shimmer` (#5675)
- [x] `face-shimmer-outline` ➜ `face-man-shimmer-outline` (#5675)
- [x] `flash-circle` ➜ `lightning-bolt-circle`
- [x] `floor-lamp-variant` ➜ `floor-lamp-torchiere-variant` (#4945)
- [x] `gif` ➜ `file-gif-box` (#5830)
- [x] `gradient` ➜ `gradient-vertical ` (#5285)
- [x] `hand` ➜`hand-front-right` (#6165)
- [x] `hand-left` ➜ `hand-back-left` (#6165)
- [x] `hand-right` ➜ `hand-back-right` (#6165)
- [x] `hinduism` ➜ `om` (#5541)
- [x] `human-greeting` ➜ `human-greeting-variant` (#6148)
- [x] `iframe` ➜ `application-brackets` (#6087)
- [x] `iframe-outline` ➜ `application-brackets-outline` (#6087)
- [x] `iframe-array` ➜ `application-array` (#6087)
- [x] `iframe-array-outline` ➜ `application-array-outline` (#6087)
- [x] `iframe-braces` ➜ `application-braces` (#6087)
- [x] `iframe-braces-outline` ➜ `application-braces-outline` (#6087)
- [x] `iframe-parentheses ` ➜ `application-parentheses ` (#6087)
- [x] `iframe-parentheses-outline` ➜ `application-parentheses-outline` (#6087)
- [x] `iframe-variable ` ➜ `application-variable ` (#6087)
- [x] `iframe-variable-outline` ➜ `application-variable-outline` (#6087)
- [x] `islam` ➜ `star-crescent` (#5541)
- [x] `judaism` ➜ `star-david` (#5541)
- [x] `monitor-clean` ➜ `monitor-shimmer` (#5400)
- [x] `pharmacy` ➜ `mortar-pestle-plus` (#5478)
- [x] `sparkles` ➜ `shimmer` (#5400)
- [x] `teach` ➜ `human-male-board` (#4959)
- [x] `television-clean` ➜ `television-shimmer` (#5400)
- [x] `text-subject` ➜ `text-long` (#4968)
- [x] `twitter-retweet` ➜ `repeat-variant` (#5455)
- [x] `voice-off` ➜ `account-voice-off` (#5269)

### When will v6 be released?
Version 6.1.95 was released on Monday, September 6th, 2021.

### What's up with your version numbers?
We do not follow semver. Our version number indicates how many icons are available in the icon pack. However, we do try to lump as many breaking changes as possible into major version releases (so every 1000 icons). We aim to add approximately 100 icons per minor version release. We sometimes make breaking changes in minor version releases, so it is always important to [look at our changelog](http://dev.materialdesignicons.com/changelog) when updating.

**Comment by Sjoerd82** [comment]
How does this impact people that use Material Design icons via frameworks, like Vuetify?

**Comment by Simran-B** [comment]
@Sjoerd82 It's a breaking change. If you upgrade to v6 you will have to change the icon names in code, unless Vuetify provides a compatibility layer. That applies to renamed icons, for removed ones you can either pick another icons if there is a suitable one, or use a third-party icon set to fill the gap like http://simpleicons.com/ for brand icons.

**Comment by Simran-B** [comment]
Should we rename the `face-woman*` icons to `face-female*` for consistency? They are the only ones with "woman" in them, and we have none with "man" (well, except pac-man...)

**Comment by goyney** [comment]
> Should we rename the `face-woman*` icons to `face-female*` for consistency? They are the only ones with "woman" in them, and we have none with "man" (well, except pac-man...)

Let's open up issues for proposed breaking changes and leave this for a summary or discussion about the changes as a whole.

**Comment by Simran-B** [comment]
`google-photos` should be removed. We don't have the latest design (see #5293) and it's a brand icon anyway. The pinwheel icons will remain.

**Comment by goyney** [comment]
I've updated #5293 and marked `google-photos` as deprecated. We'll leave `bootstrap` alone for now because it is a developer tool and that falls in the realm of our accepted icons. Consider it grandfathered in.

**Comment by Templarian** [comment]
I added a note to address finally dropping the other font files as suggested in this issue: https://github.com/Templarian/MaterialDesign-Webfont/issues/59

Going to take it one step further and only bundle Woff2 after 6.0 This means anyone targeting IE11 will need to use an older version. Almost all large companies are dropping IE11 support in 2021 so this is a good time for us.

**Comment by digitalpoin** [comment]
Please update car icon for "car door open"

**Comment by goyney** [comment]
> Please update car icon for "car door open"

@digitalpoin I'm not sure what you are asking here, please open a new issue if you have a request for a new icon or an icon update. Thank you!

**Comment by digitalpoin** [comment]
> > Please update car icon for "car door open"
> 
> @digitalpoin I'm not sure what you are asking here, please open a new issue if you have a request for a new icon or an icon update. Thank you!

Oh sorry. I am just suggesting to add an "open door car" icon in MaterialDesignIcons for the next version. Thank you in advance.

**Comment by zgover** [comment]
@goyney would you mind editing the original issue content—providing brief insights of the icon task list under  _'Icons Being Removed'_—specify either name of alternative or aliased resolution or just icon EOL decision. This will enable support for substantially greater consumer awareness while migrating; saving time, resources and energy by minimizing page navigations to the respective icon issue.

**Comment by goyney** [comment]
> @goyney would you mind editing the original issue content—providing brief insights of the icon task list under _'Icons Being Removed'_—specify either name of alternative or aliased resolution or just icon EOL decision. This will enable support for substantially greater consumer awareness while migrating; saving time, resources and energy by minimizing page navigations to the respective icon issue.

This issue serves as that reference. Each linked issue contains more information if absolutely needed. The TL;DR is that we are deprecated and removing *most* brand icons and pointing people to [SimpleIcons](https://simpleicons.org/) for brand icon needs. Brand icons carry a certain amount of risk so we are slowly reducing that surface area.

**Comment by juhasev** [comment]
I think we should take it easy on renaming and deleting icons. This is a major burden to update hundreds of icons currently in use especially the ones that got deleted.

**Comment by goyney** [comment]
> I think we should take it easy on renaming and deleting icons. This is a major burden to update hundreds of icons currently in use especially the ones that got deleted.

We do not make breaking changes lightly. However, when we do, we align them to the major breaking version change (in this case v5 ➜ v6). You are not required to update, but if you do, you will need to update any places in which you are affected by the changes. This is the case for nearly every piece of open-source software out there. Please use this issue as your migration path once v6 is released if you chose to upgrade.
