### ISSUE TITLE
RELEASED - Version 7 - Upcoming Breaking Changes

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#6504]
We are now a little over halfway through the v6 releases, so it's time to start planning our next major version release... Lucky v7!

This issue will attempt to capture any and all BREAKING CHANGES that will occur in version 7, so when we eventually do release it there aren't any surprises. Please use the information in this thread to plan any work you may need to do to prevent issues when updating to v7 in the future.

We'll keep this issue up to date and once we release v7, this issue will act as reference.

## Icons Being Removed (7)
The following icons have been deprecated and will be removed entirely:
- [x] `android-messages` (#6598)
- [x] `book-variant-multiple` (#6689)
- [x] `desktop-mac` (#6510)
- [x] `desktop-mac-dashboard`  (#6510)
- [x] `discord` (#6564)
- [x] `google-home` (#6600)
- [x] `tablet-android` (#6599)

## Icons Being Renamed (20)
The following icons are being renamed:
- [x] `diving-scuba` ➜ `diving-scuba-mask` (#6505)
- [x] `email-send` ➜ `email-arrow-right` (#6666)
- [x] `email-send-outline` ➜ `email-arrow-right-outline` (#6666)
- [x] `email-receive` ➜ `email-arrow-left` (#6666)
- [x] `email-receive-outline` ➜ `email-arrow-left-outline` (#6666)
- [x] `format-textdirection-r-to-l` ➜ `format-pilcrow-arrow-left` (#6275)
- [x] `format-textdirection-l-to-r` ➜ `format-pilcrow-arrow-right` (#6275)
- [x] `globe-light` ➜ `globe-light-outline` (#6431)
- [x] `google-controller` ➜ `controller` (#6601)
- [x] `google-controller-off` ➜ `controller-off` (#6601)
- [x] `lecturn` ➜ `lectern`(#6532)
- [x] `mosque` ➜ `mosque-outline` (#6536)
- [x] `receipt` ➜ `receipt-text` (#2168)
- [x] `receipt-outline` ➜ `receipt-text-outline` (#2168 / #6016)
- [x] `silo` ➜ `silo-outline` (#6695)
- [x] `text-to-speech` ➜ `microphone-message` (#6555)
- [x] `text-to-speech-off` ➜ `microphone-message-off` (#6555)
- [x] `timeline-help` ➜ `timeline-question` (#6603)
- [x] `timeline-help-outline` ➜ `timeline-question-outline` (#6603)
- [x] `vector-point` ➜ `vector-point-select` (#4518)

## General Changes
- [ ] We plan on turning off the SVGO option to use absolute path data. This should have no visible effect on any icon glyphs but should reduce the binary sizes of each glyph in the repository. (#5554)
- [x] We are going to remove the inclusion of a `DOCTYPE` in the raw SVG files. (#5934)

### When will v7 be released?
We currently average a release a month. At this point in time, I would expect v7 to release sometime around August 2022.

### What's up with your version numbers?
We do not follow semver. Our version number indicates how many icons are available in the icon pack. However, we do try to lump as many breaking changes as possible into major version releases (so every 1000 icons). We aim to add approximately 100 icons per minor version release. We sometimes make breaking changes in minor version releases, so it is always important to [look at our changelog](http://dev.materialdesignicons.com/changelog) when updating.

**Comment by Templarian** [comment]
We will be turning off the SVGO, but are going to do this in the 8.x release. 7.0.96 shipped the other day.
