### ISSUE TITLE
🍅 Tomato Icon (used for todo, pomodoro, timer apps)

### ISSUE THREAD

**Issue by eddieberklee** [Templarian/MaterialDesign#6579]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Can be used for pomodoro timer todo apps.

### Give us an example of what this icon might look like.

https://www.google.com/imgres?imgurl=https%3A%2F%2Fimage.shutterstock.com%2Fimage-vector%2Fvector-line-icon-tomato-260nw-1702314970.jpg&imgrefurl=https%3A%2F%2Fwww.shutterstock.com%2Fsearch%2Ftomate%2Bicon&tbnid=Ex6CxZ9CTR1ChM&vet=12ahUKEwjZn56Fy8n3AhVSATQIHb4RCXIQMygDegUIARDvAQ..i&docid=NTlS6VcIjtq_AM&w=260&h=280&q=tomato%20icon&ved=2ahUKEwjZn56Fy8n3AhVSATQIHb4RCXIQMygDegUIARDvAQ

**Comment by goyney** [comment]
Duplicate of #2005.
