### ISSUE TITLE
Inspiration from Webalys Nova icons

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#877]
http://www.nova-icons.com/ has some really good icons we currently miss. Some interesting ones:

- [ ] nuke
- [ ] feather (also see #691)
- [ ] binocular (improve #476?)
- [ ] skull (I hope we can do better)
- [ ] exit (as text -> emergency sign)
- [ ] fireplug / hydrant
- [ ] postage stamp (dotted outline better than #418?)
- [ ] express mail (hmm...)
- [ ] portrait picture (human shape like in the account icons + the corners like in the scan scan icons)
- [ ] robot (e.g. #832)
- [ ] power sockets (#752)
- [ ] wireless speaker (speaker + circle segments)
- [ ] alternative pan icon (small circle surrounded by 4 triangles pointing outwards)
- [ ] chest of drawers
- [ ] ribbon / honor badge
- [ ] satellite uplink
- [ ] antenna
- [ ] share (open hand)
- [ ] recycle / circulation (3 arrows in a circular shape)
- [ ] various arrow icons (narrower, wider, reorder, ...)
- [ ] infinity
- [ ] instruments (drums, trumpet, ...)
- [ ] umbrella closed
- [ ] DNA, atom, compound, cell (#147)
- [ ] register (#850)
- [x] balance scale (#873)
- [ ] Apple command and alt key
- [ ] globe icon (#384 / #873)
- [ ] door (#193 / #861)
- [ ] fire extinguisher (#792)
- [ ] helicopter
- [ ] shovel
- [ ] alien (#835)
- [ ] tank (#365)

**Comment by infanf** [comment]
Here are two. You may decide which versions might be better:
Apple CMD:
![apple-cmd](https://cloud.githubusercontent.com/assets/8826710/12064009/ce312ae0-afb8-11e5-9a21-98a6736b9979.png) ![apple-cmd-48](https://cloud.githubusercontent.com/assets/8826710/12064012/cffc6e0c-afb8-11e5-86e6-7623e1d08d50.png) ![apple-cmd-96](https://cloud.githubusercontent.com/assets/8826710/12064013/d1568922-afb8-11e5-9a86-a27b272adc3b.png)
![apple-cmd-alt](https://cloud.githubusercontent.com/assets/8826710/12064015/de3d1412-afb8-11e5-90b5-1757b3f7144b.png) ![apple-cmd-alt-48](https://cloud.githubusercontent.com/assets/8826710/12064016/df8d6e8e-afb8-11e5-93d3-2fec93c9ec40.png) ![apple-cmd-alt-96](https://cloud.githubusercontent.com/assets/8826710/12064017/e0b90dcc-afb8-11e5-8998-bf5d1cfbc367.png)
Exit sign:
![exit](https://cloud.githubusercontent.com/assets/8826710/12064026/1b77a6f8-afb9-11e5-923c-906a9b83791a.png) ![exit-48](https://cloud.githubusercontent.com/assets/8826710/12064028/1cab94bc-afb9-11e5-9895-355785a01fcf.png) ![exit-96](https://cloud.githubusercontent.com/assets/8826710/12064030/1dfc42f8-afb9-11e5-9e6a-705d4a8f13d6.png) 
![exit-alt](https://cloud.githubusercontent.com/assets/8826710/12064031/1f0bb1d8-afb9-11e5-928f-7ed24e77fbed.png) ![exit-alt-48](https://cloud.githubusercontent.com/assets/8826710/12064032/202a49f8-afb9-11e5-9d42-a8373cb0e731.png) ![exit-alt-96](https://cloud.githubusercontent.com/assets/8826710/12064033/2146c76c-afb9-11e5-906e-713aa943f5ac.png) (Font style as in fax https://materialdesignicons.com/icon/fax)
![exit-outline](https://cloud.githubusercontent.com/assets/8826710/12064054/9360cb40-afb9-11e5-83cb-4d48bbcccbc9.png) ![exit-outline-48](https://cloud.githubusercontent.com/assets/8826710/12064055/94a55ca0-afb9-11e5-84d1-bfa1c644e423.png) ![exit-outline-96](https://cloud.githubusercontent.com/assets/8826710/12064056/95b2a45e-afb9-11e5-8681-dfff120c75b3.png)
![exit-outline-alt](https://cloud.githubusercontent.com/assets/8826710/12064058/96c7e890-afb9-11e5-8c5d-c90b1fa30777.png) ![exit-outline-alt-48](https://cloud.githubusercontent.com/assets/8826710/12064059/978b0348-afb9-11e5-80be-8c561d9f145a.png) ![exit-outline-alt-96](https://cloud.githubusercontent.com/assets/8826710/12064060/989d4cbe-afb9-11e5-9ed1-3b6c34238a08.png)
[svgs.zip](https://github.com/Templarian/MaterialDesign/files/75498/svgs.zip)

**Comment by Templarian** [comment]
Keep in mind while you create these unlike Nova these need to be 20x20. A lot of Nova's are built on 24x24 so he has a little more room to work with.

**Comment by CoDEmanX** [comment]
True point. Google Play Store icons don't seem to obey the MD icon guidelines either.

@infanf: I prefer the first version of the apple command key.

Here's a shot at Apple's Alt key:

![apple_alt](https://cloud.githubusercontent.com/assets/1309249/12479362/e7c74718-c03a-11e5-8cb3-8ecae13bee51.png) https://www.dropbox.com/s/fymmmfjmvygqouk/apple_alt.svg?dl=0

**Comment by Templarian** [comment]
@CoDEmanX While I appreciate the effort that went into creating this issue. I'm going to close this out. Lets stick to using individual icon requests. Going to try and break up some of these larger requests. Feel free to make individual issues or re-title any of the ones above to make them easier to find.
